# Generated by Django 2.2.10 on 2021-03-21 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredusers',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
